spring.application.name=mygym
spring.datasource.url=jdbc:postgresql://localhost:5432/mygym?useSSL=false&amp;serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

